### ISSUE TITLE
Beware, major security issue

### ISSUE THREAD

**Issue by BzRk88** [InkedCurtis/FUT-Buyer#27]
Hello Curtis,

I found a major security issue with your autobuyer server. Once you know the server ip address, anyone can create an account for that installment and see your ea account data. Because all account data is visible: acount name, password, ea backup codes and not made unreadable like what you normally have for password fields. This all can be used to "hack" your ea account. I unfortunately found out the hard way, i cannot get into my ea account anymore. I had a look in the table where the users accounts are stored and there was a second one in there which of course i know nothing about.
I just want anyone who bought your autobuyer server know what a risk they are taking and maybe you can work on making it more secure. My programming skills are limited at best but for someone with a bit of knowledge it is pretty easy to find ip addresses where your autobuyer server is installed and "steal" the ea accounts.

**Comment by albertosoho** [comment]
You have to change the environment to "production" on your .env file, this is well documented.
