### ISSUE TITLE
Problem with Search function in PC and Xbox

### ISSUE THREAD

**Issue by TempsAdditionnel** [InkedCurtis/FUT-Buyer#28]
I have a problem with the autobuyer search function on Xbox and PC.
On your buyer with my Xbox account, He marks that he starts to search for the player but I don't have the event that says "search complete" so it doesn't work.
Please fix this problem.

**Comment by cengiboy4** [comment]
This also in PS4 "We are going to search for..." but no "Search completed".

**Comment by TempsAdditionnel** [comment]
So the buyer don’t work now.. Please Curtis fix this problem..

**Comment by InkedCurtis** [comment]
I've had no correlation from either of you.
